debug: false #??? ??? ??????? ????. ?????? ???? ??? ??? ?? ? ?? ??? ???? ????. ? ???? 
            #??? ??? ?? ? ?? ?? ?? ????. ?? ??? ?? ?? ???? false? ??.
            #?? logback.xml? ??? ???? ??? ?? ????.
management.endpoints.web.exposure.include: "*"
            #????? ???????? ???? ???? ??? ???? ?? ?? ??? ??

logging:
  level:
    com.fastcampus.projectboard: debug #projectboard?? ???? ?? ???? debug? ???.
    org.springframework.web.servlet: debug #request, response ??? ?? debug log? ???.
    org.hibernate.type.descriptor.sql.BasicBinder: trace #jpa ??? ??? ? ????? ? ? ??.(????? ?? = trace level)

spring:
  datasource: #db ????
    url: jdbc:mysql://localhost:3306/board
    username: uno
    password: thisisTESTpw!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true #?????? ??? ?? ??? ????? ??? ??? ? ??
    hibernate.ddl-auto: create #???? ?? ???? ddl?? ??? ??. create...
    open-in-view: false
    show-sql: true
    properties: #???????? ???? ??? properties? ??? ??????? ????? ??.
      hibernate.format_sql: true #??? ??? ???? ???? ??? ??.
      hibernate.default_batch_fetch_size: 100 #??? ??? ???? ?? ??? 100?? select?? ????.(n+1?? ??)

  h2:
    console:
      enabled: false
  sql.init.mode: always #???? ???? ?? db? ???? test db? ???? ??? ???.

---

spring:
  config.activate.on-profile: testdb #testdb profile? activate ?? ?? ? ? ??? ??? ?? ?
  #datasource:
  # url: jdbc:h2:mem:board;mode=mysql
  #  driver-class-name: org.h2.Driver
  #sql.init.mode: always
  #test.database.replace:mode
